version: "3.9"
   
services:
  postgres-db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: backend
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=daftmemes
      - DB_USER=daftmemes
      - DB_PASS=pa44w0rd
      - DB_HOST=postgres-db
      - STORAGE_TYPE=gcs
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
      - GCS_BUCKET_NAME=daft-memes
    deploy:
      restart_policy:
        condition: any
    volumes:
      - image-store:/public
      - ./credentials.json:/credentials.json
    depends_on:
      - postgres-db
  frontend:
    build: frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
    environment: 
      - REACT_APP_API_URL=http://localhost:8080
volumes:
  db-data:
  image-store: